### ISSUE TITLE
Live preview of the paid version

### ISSUE THREAD

**Issue by ghost** [adminmart/Modernize-Nextjs-Free#1]
Form elements > autocomplete, select the combo box
![Screenshot 2023-05-19 142036](https://github.com/adminmart/Modernize-Nextjs-Free/assets/134094197/ca6feb2f-3fe6-45c1-8fb8-565dd21da8db)

**Comment by adminmart** [comment]
> Form elements > autocomplete, select the combo box ![Screenshot 2023-05-19 142036](https://user-images.githubusercontent.com/134094197/239606633-ca6feb2f-3fe6-45c1-8fb8-565dd21da8db.png)

 Thanks for the contact its solved : https://modernize-nextjs-main.netlify.app/forms/form-elements/autocomplete

Thanks
